### ISSUE TITLE
Why no Python 3?

### ISSUE THREAD

**Issue by RobertPaulson90** [Gallopsled/pwntools#689] opened 2016-08-23 15:45 UTC
Just curious, not interested in a heated argument or anything like that. I just notice so many cool projects using 2.7 and I'd like to understand why

**Comment by mrschyte** [comment] 2016-08-23 16:05
I'm also in favour of a v3 version, but it seems that it's hard to support both Python v2 and v3 using the same codebase. See issue #529 for the related discussion and http://python3porting.com/noconv.html explaining some of the difficulties. There is a Python3 fork available at https://github.com/arthaud/python3-pwntools which was forked from an older version of pwntools so your mileage may vary.

**Comment by TethysSvensson** [comment] 2016-08-23 20:27
@mrschyte is correct. Getting pwntools to work in python3 is not actual all that much work. The last time I looked at it, it was the work of about a day or two to make the changes (though pwntools has grown slightly since then).

The issue was that it is very hard to support both versions at the same time in the same codebase.

I think we should look into making this work ideally while still supporting python 2, however doing so is not completely trivial.

As a side-note, my personal opinion is that the reason why you see so many cool projects using 2.7 is because the way python 3 was introduced was a mistake. Python 3 seems to be a better language in almost every way I know of, however the only real choices you have as a library maintainer is to "flip the switch" and support v3 exclusively or do twice the amount of work.

However as a library maintainer, I have no incentive to be a first mover on this. Until more than 50% of the other projects switch, I will still have a better experience and more users by sticking with python 2. There should be a better migration path than "well, just suck it up" -- preferably with python 2 and 3 interoperability.

**Comment by TethysSvensson** [comment] 2016-08-23 20:28
In any case, this is a duplicate of #529, so I am closing it.

**Closed as completed by TethysSvensson** 2016-08-23 20:28 UTC
Labels: duplicate

**Comment by zachriggle** [comment] 2016-08-24 03:02
> day or two of work

Famous last words! :-P
