### ISSUE TITLE
Latest update to Fedora 32 seems to crash gdb.debug() on 32-bit targets

### ISSUE THREAD

**Issue by Swiftloke** [Gallopsled/pwntools#1783] opened 2021-02-05 18:58 UTC
This issue likely has nothing to do with pwntools, but I'm posting it here so that it can be analyzed further, and possibly sent to the maintainers of the guilty update.

After the latest update to Fedora 32, attempting to run ``gdb.debug`` on a 32-bit program causes a segmentation fault to occur within ``__ctype_init`` in glibc. This error does not occur with 64-bit programs. The issue also does not occur when running the program directly, or through GDB without the aid of pwntools. Furthermore, the issue does not occur when launching a process through pwntools and using ``gdb.attach``.

How to reproduce:
- Install a build of Fedora 32 Workstation from the Fedora website.
- Compile this simple program:
```c
#include <stdio.h>

int main(int argc, char** argv)
{
    printf("Hello, world!");
    return 0;
} 
```

with the following commands:

```
sudo dnf install glibc-devel.i686
gcc -m32 test_case.c -o test_case 
```

- Run the following script to attempt to debug the process:

```python
from pwn import *

p = gdb.debug('./test_case')
p.interactive()  # Keep the process alive 
```
- Press "continue" in GDB and observe normal behavior.
- Run ``sudo dnf update`` and restart.
- Repeat the above behavior and observe the following segmentation fault when attempting to continue in GDB:
```Program received signal SIGSEGV, Segmentation fault.
0xf7e079eb in __ctype_init () from target:/lib/libc.so.6
```
Attached is a core dump (with a .txt extension so GitHub will upload it) and log file from pwntools. Nothing seems to be wrong with pwntools, but something has gone seriously wrong with the latest Fedora update. Maybe someone here will be able to determine the guilty factor? I spent an afternoon attempting to find the problem on my own and didn't get very far. Also attached is what changed when one updates from a fresh install of Fedora 32.

I hope someone finds this useful.

[test_case_fedora_updates.txt](https://github.com/Gallopsled/pwntools/files/5934666/test_case_fedora_updates.txt)
[test_case_log.txt](https://github.com/Gallopsled/pwntools/files/5934667/test_case_log.txt)
[test_case_dump.txt](https://github.com/Gallopsled/pwntools/files/5934694/test_case_dump.txt)

**Comment by theKidOfArcrania** [comment] 2021-02-05 21:23
I was able to reproduce this bug on latest debian bullseye as well. Furthermore looks like by running `/usr/bin/gdbserver --multi --no-disable-randomization localhost:0 <exeprog>` directly and then attaching to that from gdb, it seems like it also bugs out. Seems like it's not a pwntools bug, but rather a gdb/libc bug.

**Comment by theKidOfArcrania** [comment] 2021-02-05 22:34
Okay I narrowed down the bug, this is definitely *not* a bug with pwntools, but actually an underlying bug under how gdbserver is used:

See [test case here](https://github.com/Gallopsled/pwntools/files/5935675/test.zip)(statically-linked freestanding binary).

If you ran the binary and single-stepped with a gdbserver backend running, it will segfault on the `gs:0x14` memory. I suspect that the gdbserver is completely disregarding the `set_thread_area` syscall or messing up the `gs` segment register write. Though it is interesting to note that running through it entirely by continuing does not result in a segmentation fault for some reason. Here's my version of gdbserver for completion:
```
GNU gdbserver (Debian 10.1-1.7) 10.1.90.20210103-git
Copyright (C) 2021 Free Software Foundation, Inc.
gdbserver is free software, covered by the GNU General Public License.
This gdbserver was configured as "x86_64-linux-gnu"
```

**Comment by heapcrash** [comment] 2021-02-07 05:57
Can you please see if you can reproduce this on Ubuntu 18.04 or 20.04?  These are the best-supported distributions, and will help us determine whether this is distro-specific or a general issue.

**Comment by theKidOfArcrania** [comment] 2021-02-07 06:20
Yep ran into the same bug on ubuntu 20.04. I ran this on up-to-date software on a docker container.
![image](https://user-images.githubusercontent.com/12724920/107138423-ebe86500-68d9-11eb-972e-51d8cae0506f.png)

Of course, I did ran this with the same kernel version that I used for my other test, which *could* play part into this bug, but I doubt it.

**Comment by heapcrash** [comment] 2021-02-07 07:52
Have you tried without GEF / Pwndbg to make sure they're not causing any issues?

**Comment by theKidOfArcrania** [comment] 2021-02-07 08:52
Yeah i've tried running gdb with --nh before to disable any .gdbinit stuff (i.e. GEF/pwndbg) and it produces the same error.

**Comment by martinclauss** [comment] 2021-02-11 06:14
I also get this error with 32bit binaries on Fedora 32, Kali Linux and Ubuntu 20.04. 64bit binaries run without any problems.

**Comment by Swiftloke** [comment] 2021-02-11 13:49
I attempted to update Fedora again by locking the ``gdb`` and ``gdbserver`` binaries with DNF versionlock:
```sudo dnf versionlock add gdb gdb-gdbserver```
However, after the update, the crash still occurs within gdbserver, implying that something even higher up the stack than gdbserver may be causing the issue.
Unfortunately, DNF has somehow rendered itself unable to undo the updates that occurred, so it seems that I'm stuck with this behavior for now unless I want to reinstall my OS once again.

Side note: A bug has been filed on Debian's gdbserver page for this issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=982049

**Comment by theKidOfArcrania** [comment] 2021-02-24 02:25
Found the commit in question that fixed it in the upstream gdb/gdbserver project (using the power of bisecting):

https://sourceware.org/git/?p=binutils-gdb.git;a=commitdiff;h=037e8112b9794a633248e5aa5943f3be273e0a20

Looks like the linux kernel version >5.9 also has something to play with the underlying issue:

> Before linux kernel version 5.9, the value used by PTRACE_SETREGS for $gs_base was ignored, but starting version 5.9, the linux kernel has support for intel architecture extension FSGSBASE, which allows users to modify $gs_base, and consequently PTRACE_SETREGS can no longer ignore the $gs_base value.

And it looks like it has something to do with the fs/gs base stuff.

And it looks like this fix was made after gdb 10.1 version, so looks like we'll have to wait for a bit to get this particular issue resolved on all the distros. Maybe it's time to ask the distros to do a backport...

**Comment by vincemann** [comment] 2021-05-24 21:04
I am still experiencing the same issue on:
Linux kali 5.10.0-kali7-amd64 #1 SMP Debian 5.10.28-1kali1 (2021-04-12) x86_64 GNU/Linux
gdbserver --version: GNU gdbserver (Debian 10.1-1.7) 10.1.90.20210103-git
gdb --version: GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git

Any updates or workarounds??

**Comment by theKidOfArcrania** [comment] 2021-05-24 22:16
Your best fix would probably be to just get the latest version of gdb/gdbserver and run those, if you _really_ want to use the gdb.attach functionality, or just stick to attaching to process via `gdb -p <pid>` (which doesn't invoke the gdbserver bug). Your version of gdb/gdbserver is actually a Jan 3 2021 build, which happens just before this Jan 20 patch.

**Comment by heapcrash** [comment] 2021-05-24 22:34
You can also use gdb.attach() to avoid the need for gdbserver, e.g.

io = process('sh')
gdb.attach(io)

That said, this sounds like a GDB problem and has nothing at all to do with
Pwntools (as OP stated).  Check to see if Fedora has an updated gdbserver
package, or try building it yourself from source.

**Comment by vincemann** [comment] 2021-05-25 16:56
Thanks for the fast replies.

I would really like to use the 'io = pwnlib.gdb.debug([binary], api=True)' version and not attach.
I have now built the latest version of gdb/gdbserver from sources:
gdb --version: GNU gdb (GDB) 10.2
gdbserver --version: GNU gdbserver (GDB) 10.2
I am still getting this error for a simple hello world c program compiled with gcc -m32:
'Reading /lib/i386-linux-gnu/libc.so.6 from remote target...
Program received signal SIGSEGV, Segmentation fault.
0xf7dd13f7 in __GI___ctype_init () at ctype-info.c:31
31 ctype-info.c: No such file or directory.'
when executing this simple pwntools code:
`from pwn import *
binary = "/path/to/my/binary"

context.binary = binary
context.terminal = ["tmux", "splitw", "-h"]

io = pwnlib.gdb.debug([binary], api=True)
io.gdb.execute("b *main")
io.gdb.continue_and_wait()
`
(I run tmux before running the pwn script)
The code works fine when I compile the hello world binary for 64bit target (without -m32).

Some more info about my setup:
gdb -batch -ex 'python import sys; print(sys.version)' : 3.9.2 (default, Feb 28 2021, 17:03:44)
python --version: Python 3.9.2

I know this is not really pwntools business, but I'd still appreciate some more hints/ideas if you have any.

**Comment by martinclauss** [comment] 2021-05-28 13:37
Hi!

Try: https://sourceware.org/pub/gdb/snapshots/current/gdb-weekly-11.0.50.20210528.tar.xz It just tested it with a 32 bit binary that broke gdbserver before and it now works :)

1) remove old gdb / gdbserver (e.g. `apt-get remove gdb gdbserver`)

2) build from source (`build-essential`, `wget` etc. packages required)

```
$ sudo apt-get install -y libgmp-dev texinfo

$ cd /tmp && \
wget https://sourceware.org/pub/gdb/snapshots/current/gdb-weekly-11.0.50.20210528.tar.xz && \
tar xf gdb-weekly-11.0.50.20210528.tar.xz && \
cd gdb-11.0.50.20210528 && \
./configure && make -j8 && sudo make install
```

check the versions

```
$ gdb --version
GNU gdb (GDB) 11.0.50.20210528-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ gdbserver --version
GNU gdbserver (GDB) 11.0.50.20210528-git
Copyright (C) 2021 Free Software Foundation, Inc.
gdbserver is free software, covered by the GNU General Public License.
This gdbserver was configured as "x86_64-pc-linux-gnu"
```

make sure it says `11.0.50.20210528-git`

Try your 32 bit binary with gdbserver and/or pwntools!

```
# one terminal window
$ gdbserver 0.0.0.0:1234 /path/to/your/binary32

# second terminal window
$ gdb
(gdb) target remote :1234
(gdb) b main
(gdb) c
(gdb) ni
...
```

Package names for Fedora are a bit different but I assume that it'll also work.

Apart from that we'll have to wait for a stable release and the package maintainers of your favorite distro ;-)

Best
Martin

**Comment by vincemann** [comment] 2021-05-28 19:08
Thanks a lot that did the trick! :)

**Comment by orkinyo** [comment] 2021-09-03 11:39
> Hi!
> 
> Try: https://sourceware.org/pub/gdb/snapshots/current/gdb-weekly-11.0.50.20210528.tar.xz It just tested it with a 32 bit binary that broke gdbserver before and it now works :)
> 
> 1. remove old gdb / gdbserver (e.g. `apt-get remove gdb gdbserver`)
> 2. build from source (`build-essential`, `wget` etc. packages required)
> 
> ```
> $ sudo apt-get install -y libgmp-dev texinfo
> 
> $ cd /tmp && \
> wget https://sourceware.org/pub/gdb/snapshots/current/gdb-weekly-11.0.50.20210528.tar.xz && \
> tar xf gdb-weekly-11.0.50.20210528.tar.xz && \
> cd gdb-11.0.50.20210528 && \
> ./configure && make -j8 && sudo make install
> ```
> 
> check the versions
> 
> ```
> $ gdb --version
> GNU gdb (GDB) 11.0.50.20210528-git
> Copyright (C) 2021 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> $ gdbserver --version
> GNU gdbserver (GDB) 11.0.50.20210528-git
> Copyright (C) 2021 Free Software Foundation, Inc.
> gdbserver is free software, covered by the GNU General Public License.
> This gdbserver was configured as "x86_64-pc-linux-gnu"
> ```
> 
> make sure it says `11.0.50.20210528-git`
> 
> Try your 32 bit binary with gdbserver and/or pwntools!
> 
> ```
> # one terminal window
> $ gdbserver 0.0.0.0:1234 /path/to/your/binary32
> 
> # second terminal window
> $ gdb
> (gdb) target remote :1234
> (gdb) b main
> (gdb) c
> (gdb) ni
> ...
> ```
> 
> Package names for Fedora are a bit different but I assume that it'll also work.
> 
> Apart from that we'll have to wait for a stable release and the package maintainers of your favorite distro ;-)
> 
> Best
> Martin

Great solution!
It should be noted that you may want to use `"./configure --with-python=/path/to/python-executable"` if you would like gdb to have support for python (for example, Pwndbg won't work without it).

**Comment by secure-77** [comment] 2021-12-22 09:01
> Can you please see if you can reproduce this on Ubuntu 18.04 or 20.04? These are the best-supported distributions, and will help us determine whether this is distro-specific or a general issue.

can confirm this issue is also in the latest stabel Ubuntu Version (20.04.3-desktop-amd64) which ships gdb and gdbserver in version 9.2.  can also confirm that it is really a problem of the gdbserver version, only using a latest gdb version does not help.
gdbversion 10.1-2 also does NOT work for me.

Building and installing gdb and gdbserver in version 11.1 will fix this issue.

**Comment by IdanBanani** [comment] 2022-02-21 14:17
> Hi!
> 
> Try: https://sourceware.org/pub/gdb/snapshots/current/gdb-weekly-11.0.50.20210528.tar.xz It just tested it with a 32 bit binary that broke gdbserver before and it now works :)
> 
> 1. remove old gdb / gdbserver (e.g. `apt-get remove gdb gdbserver`)
> 2. build from source (`build-essential`, `wget` etc. packages required)
> 
> ```
> $ sudo apt-get install -y libgmp-dev texinfo
> 
> $ cd /tmp && \
> wget https://sourceware.org/pub/gdb/snapshots/current/gdb-weekly-11.0.50.20210528.tar.xz && \
> tar xf gdb-weekly-11.0.50.20210528.tar.xz && \
> cd gdb-11.0.50.20210528 && \
> ./configure && make -j8 && sudo make install
> ```
> 
> check the versions
> 
> ```
> $ gdb --version
> GNU gdb (GDB) 11.0.50.20210528-git
> Copyright (C) 2021 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> $ gdbserver --version
> GNU gdbserver (GDB) 11.0.50.20210528-git
> Copyright (C) 2021 Free Software Foundation, Inc.
> gdbserver is free software, covered by the GNU General Public License.
> This gdbserver was configured as "x86_64-pc-linux-gnu"
> ```
> 
> make sure it says `11.0.50.20210528-git`
> 
> Try your 32 bit binary with gdbserver and/or pwntools!
> 
> ```
> # one terminal window
> $ gdbserver 0.0.0.0:1234 /path/to/your/binary32
> 
> # second terminal window
> $ gdb
> (gdb) target remote :1234
> (gdb) b main
> (gdb) c
> (gdb) ni
> ...
> ```
> 
> Package names for Fedora are a bit different but I assume that it'll also work.
> 
> Apart from that we'll have to wait for a stable release and the package maintainers of your favorite distro ;-)
> 
> Best Martin
Thank you.
Any reason why you picked version 11 and not 12 (release version)?
It worked for me with 
https://sourceware.org/pub/gdb/releases/gdb-11.2.tar.xz

**Comment by secure-77** [comment] 2022-02-21 19:26
> Any reason why you picked version 11 and not 12 (release version)?
> It worked for me with
> https://sourceware.org/pub/gdb/releases/gdb-11.2.tar.xz

Maybe because there is no version 12 and Version 11.2 was not released at the point, the post was created ;)
https://www.sourceware.org/gdb/news/

**Comment by peace-maker** [comment] 2023-07-27 21:19
Closing this now since it's not a bug in pwntools. If you see this problem, see above for details - you need a newer gdb+gdbserver version, maybe newer than your distribution has packaged. Installing from source helped!

**Closed as completed by peace-maker** 2023-07-27 21:19 UTC
Labels: bug, backport-required

**Comment by secure-77** [comment] 2023-07-27 22:03
Just if anybody want to know more about this issue or how to update the server, Its been a while, but I created a blog post about this: https://secure77.de/pwntools-gdb-gdbserver-and-pwndbg-with-32-bit-binaries/
