### ISSUE TITLE
Instalation problem sortedcontainers<3.0,>=2.0

### ISSUE THREAD

**Issue by p702** [Gallopsled/pwntools#1245] opened 2019-01-02 04:44 UTC
Hi 
I try to install pwn tools in Kali 64 bits in Ubuntu 14 and now in the 16 version  by using the comands this 
apt-get update
apt-get install python2.7 python-pip python-dev git libssl-dev libffi-dev build-essential
pip install --upgrade pip
pip install --upgrade pwntools

But always the same error when i use pip install --upgrade pwntools 

ERROR 
"intervaltree 3.0.2 has requirement sortedcontainers<3.0,>=2.0, but you'll have sortedcontainers 1.5.10 which is incompatible."

could you helpme please ???

**Comment by CipherCloak** [comment] 2019-01-04 01:43
Same error here. Some info:
Kali 2018.4
![pwntools-error](https://user-images.githubusercontent.com/3332674/50670241-a3df1180-0fa0-11e9-8974-3ea8109f9c85.PNG)

**Comment by p702** [comment] 2019-01-04 02:57
Yes pedro bro i try so many things to solve reinstall install lower versions of the sorted packet and the other intervaltree and nothing the error persist i dont know how to instal pwn tools :(

**Comment by CipherCloak** [comment] 2019-01-04 04:21
According to "setup.py" the problem is not in "pwntools".
See this: https://github.com/Gallopsled/pwntools/issues/1154

I'll try some workaround tomorrow.
Bye... time to sleep :)

**Comment by ghost** [comment] 2019-01-04 13:15
it doesn't work on manjaro either

**Comment by iweizime** [comment] 2019-01-07 18:26
It seems that intervaltree has already updated its requirement about sortedcontainers. But Pwntools still use sortedcontainers<2.0 to avoid #1154.

**Comment by zachriggle** [comment] 2019-01-07 21:17
The fix for this landed on `stable` a few weeks ago but I didn't get around to cutting a new release yet.

**Comment by zachriggle** [comment] 2019-01-08 00:57
This should be resolved in 3.12.2.

**Closed as completed by zachriggle** 2019-01-08 00:57 UTC

**Comment by p702** [comment] 2019-01-13 06:18
Thank you very much every one install the pip install intervaltree==2.1.0  solve the issue thanks for the support again
