### ISSUE TITLE
Capitalized word is not shown with pwntools and argparse

### ISSUE THREAD

**Issue by brunomcuesta** [Gallopsled/pwntools#1856] opened 2021-03-29 04:14 UTC
Hello, I made a script to show information with pwntools and argparse. The problem is that if I capitalize a word, the argparse does not receive the argument. Maybe it's a more in-depth problem like sys.argv.
I am using the latest version of pwntools.

## The Code

```python
#!/usr/bin/python
# -*- coding: utf-8 -*-

from pwn import *
import argparse


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-H', '--hash', required=True, type=str.lower)
    parser.add_argument('-w', '--wordlist', required=True)
    parser.add_argument('-t', '--type', choices=['md5', 'sha1', 'ntlm'], type=str.lower, required=True)
    params = parser.parse_args()
    info('Test info message')
    print(params)
```

## Executing the command

```sh
$ python test.py -H ABCD -w /usr/share/wordlists/rockyou.txt -t ntlm
```

## Output

```
usage: test.py [-h] -H HASH -w WORDLIST -t {md5,sha1,ntlm}
test.py: error: argument -H/--hash: expected one argument
```

## Behavior

If I remove the import from pwntools the argparse takes the argument and shows the word in lower case.
I just imported the log and info from pwn, the problem persists.

## System Info
OS: Parrot (last version)
Terminal: xfce terminal
Extra: tmux (terminal multiplexer)
Pwntools version: pwntools==4.3.1
Python version: 3.9.2

I tested with and without tmux.

## Print

![2021-03-29_00-38](https://user-images.githubusercontent.com/816237/112785417-51c7b200-902a-11eb-9f88-cfcdc7d2d293.png)

**Comment by heapcrash** [comment] 2021-03-29 04:17
This is because of what happens when you "from pwn import *".

There is a module, pwnlib.args, that automagically converts "python
script.py FOO BAR=3" to give "pwnlib.args.FOO" and "pwnlib.args.BAR".

This cannot be turned off, but you can work around it by:
* Do not use "from pwn import *" but rather import what you need
specifically from pwnlib
* Invoke your argparse before "from pwn import *"

**Comment by brunomcuesta** [comment] 2021-03-29 04:27
I wanted to use argparse because of the menu it has with the script information.
I changed the system, and in Debian 10 the same problem occurs. I just imported the "info" and placed the argparse import above pwntools.

## Print
![2021-03-29_01-23](https://user-images.githubusercontent.com/816237/112786926-bcc6b800-902d-11eb-9fc7-b103e3b17796.png)

**Comment by heapcrash** [comment] 2021-03-29 04:40
"from pwn" still causes everything to be imported.

You need to "from pwnlib.log import info" and probably also "from
pwnlib.log import install_default_handler" and "install_default_handler()"
to get what you want.

I recommend simply parsing the arguments before importing anything from
pwntools -- not just declaring the parser, but literally call parse_args()
before you import anything from pwntools.

**Comment by Arusekk** [comment] 2021-03-29 08:25
There is also another way:
```py
import pwnlib.args
pwnlib.args.free_form = False
from pwn import *
```
and voila!

Pwntools does it internally, whenever argparse is really needed:
https://github.com/Gallopsled/pwntools/blob/ec9dfe108b85ac47983e9a98808fcdbb50cb0cdd/pwnlib/commandline/asm.py#L5-L12

Closing as this is intended behaviour and you should now have enough info to deal with it correctly.

**Closed as completed by Arusekk** 2021-03-29 08:25 UTC
Labels: bug, backport-required
