### ISSUE TITLE
execve bug

### ISSUE THREAD

**Issue by rommarius** [Gallopsled/pwntools#2411] opened 2024-05-23 18:32 UTC
cant spawn a shell with arguments
```
rop = ROP(program, base=0x00007fffffffe400)
rop.call('execve', [b'/bin/sh', [[b'/bin/sh'], [b'-p'], [b'-c'], [b'ls']], 0])
chain_1  = b''
chain_1 += b'\x00'*136 # chain_1 += b'B'*6
chain_1 += rop.chain()
print(rop.dump())
```

with null terminated array also didn't work
```
rop.call('execve', [b'/bin/sh', [[b'/bin/sh'], [b'-p'], [b'-c'], [b'ls'], 0], 0])
```

this seems to work but complex parameters didn't
```
rop = ROP(program)
rop.execve(bin_sh, 0, 0)
chain_1  = b''
chain_1 += b'\x00'*136 # chain_1 += b'B'*6
chain_1 += rop.chain()
```

**Comment by peace-maker** [comment] 2024-05-23 22:44
This appears to be a duplicate of #2409

**Comment by peace-maker** [comment] 2024-10-03 10:13
Make sure your `base` pointer points at the start of your ropchain.

**Closed as completed by peace-maker** 2024-10-03 10:13 UTC
Labels: bug, backport-required
