### ISSUE TITLE
ROP stack alignment issues on x64

### ISSUE THREAD

**Issue by JBYoshi** [Gallopsled/pwntools#1870] opened 2021-04-25 03:31 UTC
Recent versions of GCC (4.5 and later) for Linux x64 require the stack to be aligned on a 16-byte boundary when calling functions. Most of the time, 8 bytes works fine; this happens pretty often when working with ROP chains. However, some functions (notably certain implementations of `system()` in libc - I'm testing on https://libc.rip/download/libc6_2.31-0ubuntu9.1_amd64.so) use an instruction called `movaps` with stack addresses, which depends on this 16-byte alignment and segfaults if the alignment is off.

With pwntools' `ROP` class, a simple workaround is to add a `ret` gadget when necessary (`rop.call(rop.find_gadget(["ret"]))`). However, it's only necessary when a function call is at an odd index in the ROP chain, which varies based on how it's constructed. Since pwntools handles the construction of the ROP chain, would it be possible for pwntools to also automatically compensate for this?

This may also affect other platforms - Wikipedia's [list of x86 calling conventions](https://en.wikipedia.org/wiki/X86_calling_conventions) also mentions 16-byte alignment for Windows x64 and (apparently due to a bug) Linux IA-32.

More info [here](https://stackoverflow.com/a/54399217).

(Not sure if this should be classified as a feature request or a bug. I'm putting it as a feature request for now since people seem to have gotten along fine without it so far.)

**Comment by heapcrash** [comment] 2021-05-31 00:57
There's nothing that can really be done here, since Pwntools has no way to know the initial stack alignment.  This is something that will have to be done manually.  Having pwntools try to do it automatically would also likely add extra padding to basic ROP gadgets when it really only needs to be done on a function call -- and while we do know if we're returning to a function or a gadget (depending on how you build the ROP object) there's not really a unified way to do this.

I'd be willing to accept a pull request that implements this, but I don't think I or @Arusekk have time for it at the moment.

**Comment by peace-maker** [comment] 2021-06-01 20:54
As a side-note: `rop.call(rop.find_gadget(["ret"]))` can be written as `rop.call(rop.ret)`, which helps with the unnecessary typing.

**Comment by mariuszskon** [comment] 2021-06-02 00:57
(Shameless plug for a project I haven't had the opportunity to work on for a while)

[autorop](https://github.com/mariuszskon/autorop), which uses pwntools, handles stack alignment in its payload builder automatically, see https://github.com/mariuszskon/autorop/blob/master/autorop/arutil/align_call.py

**Comment by Arusekk** [comment] 2022-08-06 16:06
I guess this is a duplicate of #1394, and... @heapcrash is right, pwntools cannot do much about it.  So until there is some creative solution to this, closing as a WONTFIX.

**Closed as not planned by Arusekk** 2022-08-06 16:06 UTC
Labels: feature, rop

**Comment by huberteff** [comment] 2026-03-22 12:32
this is still an issue with pwntools 4.15.0 
Is there any chance to get this fixed and prevent the need to add manual alignment gadgets?

(with amd64)

**Comment by Arusekk** [comment] 2026-05-14 22:57
@huberteff How do you think this should be solved?

Sometimes we do know the base (it can be supplied to ROP constructor). The simplest we can do is assume that the ABI requires 16-byte stack alignment always, and guess that the first ROP entry is a return address adhering to the ABI (so base is an odd multiple of 8). We would then add a single ret gadget before every call that did not get the lucky alignment. This obviously has trade-offs. The ROP chain can get longer, and also the initial guess can be wrong. But it should not hurt in general.

Another approach would be to inspect functions for SSE instructions, or match some common function names against a list. What do you think?

**Comment by huberteff** [comment] 2026-05-15 22:02
@Arusekk i'm not very familiar in that department - yes, some heuristics may help, and yes they may be wrong. I have no strong idea how to make this rock solid (other than leaving this in the current state and have the user figure it out for their individual case at hand)
