### ISSUE TITLE
pwn command not found on OSX

### ISSUE THREAD

**Issue by h4sh5** [Gallopsled/pwntools#1863] opened 2021-04-14 06:42 UTC
trying to run the `pwn` command on OSX terminal doesn't work.
I have tried installing pwn tools via multiple ways (using pip3, or cloning the git repo), and confirming that it works (`from pwn import *` in python3 works)

I also checked in ~/.local, and /usr/local/bin/, and even ~/Library/Python/3.8/bin/ by using `find`. Any idea what the issue might be?

I am running an intel mac book on 10.15.7

**Comment by Arusekk** [comment] 2021-04-14 08:08
What do you get from `echo $PATH`?

**Comment by heapcrash** [comment] 2021-04-15 21:00
Works for me with the system-installed Python

```
$ uname
Darwin

$ /usr/bin/python3 -m pip install pwntools
...

$ which pwn
/Users/heapcrash/Library/Python/3.8/bin/pwn
```

And when using pyenv

```
$ pyenv local 3.8.8

$ pip3 install pwntools
...

$ which pwn
/Users/heapcrash/.pyenv/shims/pwn
```

**Comment by Arusekk** [comment] 2021-04-20 09:59
I assume this is a duplicate of #1801

**Closed as completed by Arusekk** 2021-04-20 09:59 UTC
Labels: bug, backport-required
