### ISSUE TITLE
Why pwntools didn't support ubuntu 14.04 i386

### ISSUE THREAD

**Issue by skyel1u** [Gallopsled/pwntools#764] opened 2016-10-12 11:58 UTC
![sp20161012_195326](https://cloud.githubusercontent.com/assets/16306294/19309234/3da37d4a-90b6-11e6-8f2d-cf47dee2bc96.png)

**Comment by TiberiumPY** [comment] 2016-10-12 13:52
Please, mention your architecture, it seems to be an architecture support issue

**Comment by zachriggle** [comment] 2016-10-12 16:11
Pwntools does not support 32-bit Python.

https://github.com/Gallopsled/pwntools/blob/0ce21d9b4593cc270ed113bf82a4e6da405b6653/pwn/__init__.py#L10-L14

This is a duplicate of #518

**Closed as completed by zachriggle** 2016-10-12 16:11 UTC
