### ISSUE TITLE
`ELF` failing to populate libraries

### ISSUE THREAD

**Issue by clubby789** [Gallopsled/pwntools#1909] opened 2021-06-02 19:14 UTC
Pwntools seems to be failing to populate the `libs` property, meaning the `libc` property also does not work.
Script:
```py
from pwn import *
e = ELF("/bin/bash")
print(e.libc)
print(e.libs)
```

## Debug Output
```
================================================================================
= Started at 2021-06-02T20:06:31                                               =
= sys.argv = [                                                                 =
=   'poc.py',                                                                  =
= ]                                                                            =
================================================================================
2021-06-02T20:06:31:INFO:pwnlib.elf.elf:'/bin/bash'
Arch:     amd64-64-little
RELRO:    Full RELRO
Stack:    Canary found
NX:       NX enabled
PIE:      PIE enabled
2021-06-02T20:06:31:INFO:pwnlib.tubes.process.process.140376457550432:Starting local process '/tmp/tmp78307f48'
2021-06-02T20:06:31:INFO:pwnlib.tubes.process.process.140376457550432:Starting local process '/tmp/tmp78307f48': pid 9699
2021-06-02T20:06:31:INFO:pwnlib.tubes.process.process.140376457550432:Receiving all data
2021-06-02T20:06:31:INFO:pwnlib.tubes.process.process.140376457550432:Receiving all data: 0B
2021-06-02T20:06:31:INFO:pwnlib.tubes.process.process.140376457550432:Process '/tmp/tmp78307f48' stopped with exit code 0 (pid 9699)
2021-06-02T20:06:31:INFO:pwnlib.tubes.process.process.140376457550432:Receiving all data: Done (0B)
================================================================================
= Started at 2021-06-02T20:06:31                                               =
= sys.argv = [                                                                 =
=   'poc.py',                                                                  =
= ]                                                                            =
================================================================================
```

## Verify on Ubuntu
The issue is the same.

**Comment by Arusekk** [comment] 2021-06-02 19:44
Known issue, Linus Torvalds refused to fix it. Duplicate of #1871

**Closed as completed** 2021-06-02 19:50 UTC
Labels: bug, backport-required
