### ISSUE TITLE
AssertionError importing pwn on 32 bit ubuntu

### ISSUE THREAD

**Issue by sferrini** [Gallopsled/pwntools#801] opened 2016-11-30 10:57 UTC
```
ubuntu@ubuntu-xenial:~/tools$ uname -a
Linux ubuntu-xenial 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:59 UTC 2016 i686 i686 i686 GNU/Linux
```

```python
ubuntu@ubuntu-xenial:~/tools$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pwn import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/tools/pwntools/pwn/__init__.py", line 2, in <module>
    from .toplevel import *
  File "/home/ubuntu/tools/pwntools/pwn/toplevel.py", line 20, in <module>
    import pwnlib
  File "/home/ubuntu/tools/pwntools/pwnlib/__init__.py", line 40, in <module>
    importlib.import_module('.%s' % module, 'pwnlib')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/tools/pwntools/pwnlib/dynelf.py", line 54, in <module>
    from . import elf
  File "/home/ubuntu/tools/pwntools/pwnlib/elf/__init__.py", line 1, in <module>
    from .corefile import Core
  File "/home/ubuntu/tools/pwntools/pwnlib/elf/corefile.py", line 13, in <module>
    from .datatypes import *
  File "/home/ubuntu/tools/pwntools/pwnlib/elf/datatypes.py", line 544, in <module>
    assert ctypes.sizeof(elf_prstatus_amd64) == 0x150
AssertionError
>>>
```

I have all the dependencies and the latest `pwntools` from `pip`.

On a 64 bit VM instead it's working fine

**Comment by LeadroyaL** [comment] 2016-12-01 04:05
Yes, I also have this problem when I use `pip install` 

My PC:
win10 64bit
virtualbox 5.2
both Ubuntu14.04/Ubuntu16.04 32bit have this problem.

**Comment by zachriggle** [comment] 2016-12-01 04:08
This is a duplicate of #518

**Closed as completed by zachriggle** 2016-12-01 04:08 UTC
Labels: duplicate
