### ISSUE TITLE
install 

### ISSUE THREAD

**Issue by yzcmf** [Gallopsled/pwntools#2262] opened 2023-09-09 06:58 UTC
File "/root/tutorial-env/lib/python3.11/site-packages/pwnlib/elf/corefile.py", line 79, in <module>
 from elftools.common.py3compat import bytes2str
ModuleNotFoundError: No module named 'elftools.common.py3compat'

solution 
-> from elftools.common.py3compat not exists anymore and the bytes2str is now moving into elftools.common.utils
-> change '/root/tutorial-env/lib/python3.11/site-packages/pwnlib/elf/corefile.py' line 79 -> from elftools.common.utils import bytes2str

**Comment by peace-maker** [comment] 2023-09-09 08:42
Thank you for your report! You can follow the fix in #2261.
Duplicate of #2260

**Closed as completed by peace-maker** 2023-09-09 08:42 UTC
Labels: bug, backport-required
