### ISSUE TITLE
Corefile error with run_assembly

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#1233] opened 2018-12-12 00:20 UTC
`run_assembly(shellcraft.trap()).corefile` explodes because we are trying to map a TON of zeroes.

Faults on:

```py
data += '\x00' * zeroed
```

Where e.g. `zeroed == 0xffcf7400`

**Comment by heapcrash** [comment] 2020-06-05 07:25
This doesn't happen anymore, mostly because `trap` causes a segfault at address `0x0` but I can't reproduce this anyway so I'm closing it

**Closed as completed by heapcrash** 2020-06-05 07:25 UTC
Labels: help-wanted
