### ISSUE TITLE
cyclic -l 0x6261616b TypeError: 'in <string>' requires string as left operand, not int

### ISSUE THREAD

**Issue by Question-h** [Gallopsled/pwntools#1496] opened 2020-05-01 13:22 UTC
$cyclic -l 0x6261616b
Traceback (most recent call last):
  File "/home/question/.local/bin/cyclic", line 8, in <module>
    sys.exit(main())
  File "/home/question/.local/lib/python3.5/site-packages/pwnlib/commandline/common.py", line 32, in main
    pwnlib.commandline.main.main()
  File "/home/question/.local/lib/python3.5/site-packages/pwnlib/commandline/main.py", line 54, in main
    commands[args.command](args)
  File "/home/question/.local/lib/python3.5/site-packages/pwnlib/commandline/cyclic.py", line 75, in main
    if not all(c in alphabet for c in pat):
  File "/home/question/.local/lib/python3.5/site-packages/pwnlib/commandline/cyclic.py", line 75, in <genexpr>
    if not all(c in alphabet for c in pat):
TypeError: 'in <string>' requires string as left operand, not int

**Comment by Welteam** [comment] 2020-05-07 21:04
Same issue here

**Comment by layderv** [comment] 2020-05-12 15:43
What version are you using? I'm using the latest one and I can't reproduce this

**Comment by Arusekk** [comment] 2020-05-28 21:25
This is fixed on dev and beta, though still present on stable.

**Comment by Arusekk** [comment] 2020-06-03 17:33
This is to be cherry-picked from 71e9c038f and f834ce95

**Closed as completed** 2020-06-03 21:32 UTC
Labels: bug, backport-required, command-line
