### ISSUE TITLE
aarch64 pwnlib.shellcraft.pushstr_array() casuses bus error

### ISSUE THREAD

**Issue by elay108** [Gallopsled/pwntools#2284] opened 2023-09-29 19:45 UTC
Hey,
The pwnlib.shellcraft.pushstr_array() causes stack misalignment when pushing pointes and causes a bus error when executed.

As seen [here](https://community.arm.com/arm-community-blogs/b/architectures-and-processors-blog/posts/using-the-stack-in-aarch32-and-aarch64):
```
For AArch64, sp must be 16-byte aligned whenever it is used to access memory.
This is enforced by AArch64 hardware.
```

However, the code generated by pwnlib.shellcraft.pushstr_array() causes sp to be misaligned by 8.
Here's the output of the function:
![carbon](https://github.com/Gallopsled/pwntools/assets/7428480/ea3cd184-6aec-4de5-9167-40cdb22846d2)

The bug happens at line 14, and the bus error is thrown at line 19. Line 14 uses str register to memory with an exclamation mark, thus causing sp to be misaligned by 8 bytes when pushing the first pointer. At line 19, there's another usage of str register to memory to push the second pointer, when sp is misaligned, thus throwing a bus error. This should be fixed by not "pushing" the pointers to the stack, but rather allocating 16-byte aligned memory on the stack (decreasing sp), then writing the pointers without modifying sp, and then adding a null byte padding if necessary.

**Comment by peace-maker** [comment] 2023-10-02 12:55
This seems like a duplicate of #2160

**Closed as completed** 2024-02-04 15:34 UTC
Labels: bug, backport-required
