### ISSUE TITLE
Out of memory...possibly due to DynELF

### ISSUE THREAD

**Issue by RobertLarsen** [Gallopsled/pwntools#485] opened 2015-03-13 13:10 UTC
I get out of memory when reallocating DynELF. More specifically her:

```python
    def _find_linkmap_assisted(self, path):
        """Uses an ELF file to assist in finding the link_map.
        """
        if isinstance(path, ELF):
            path = path.path

        # Load a fresh copy of the ELF
        with context.local(log_level='error'):
            elf = ELF(path)  #<----Right here
        elf.address = self.libbase
```
...well, in a fork() call further down the call stack.
Why is the ELF object reallocated? This will call on to readelf/objdump/whatever. Should not be necessary, or am I missing something?

Could it not simply be:
```python
        if isinstance(path, ELF):
            elf = path
            path = path.path
        else:
            with context.local(log_level='error'):
                elf = ELF(path)
```

**Comment by zachriggle** [comment] 2015-03-13 16:24
Probably.  I've made some enhancements to the regression testing framework recently to make it much more robust.  I'm currently running into issues with MIPS DynELF but will soon contribute that back in a PR.  I'll try out this change :)

**Comment by Idolf** [comment] 2016-07-02 22:33
@RobertLarsen : Does this reproduce in the current master?

**Comment by zachriggle** [comment] 2016-07-26 14:34
Closing since it's 1 year+ old and no repro case is available.

There's no circumstances where we should be forking or shelling out to readelf/objdump/etc, so I'm not seeing where this happens.

`strace -e fork,execve checksec /bin/sh` shows that after the Python interpreter is invoked, there are no calls to either `fork` or `execve` when loading an ELF.

**Closed by zachriggle** 2016-07-26 14:34 UTC
