### ISSUE TITLE
Make recvregex() greedy

### ISSUE THREAD

**Issue by gsingh93** [Gallopsled/pwntools#472] opened 2015-02-12 05:38 UTC
`recvregex()` should do a greedy match (or there should be an option to do so). This is tricky with network functions because you don't know when you're going to get the last byte, but I think it could still be possible.

**Comment by zachriggle** [comment] 2015-02-12 11:40
This could only work if a timeout was provided.  All data would be received until the timeout expired, after which time the regex could be run on all available data.

**Comment by gsingh93** [comment] 2015-02-12 18:41
Yup, a timeout is exactly what I was thinking of.

I wasted a bunch of time on a challenge where the input was `N=([0-9]+) C=([0-9]+)`. Instead of receiving `N=485 C=10` like expect from normal regex parsing, I kept receiving `N=485 C=1`. It took me a while to realize the regex wasn't greedy since every other regex system I've used is greedy by default.

**Comment by zachriggle** [comment] 2015-02-12 19:16
A few things that might help in the future:

1. Turn on debugging.  This can be done at runtime with `context.log_level='debug'` or globally with the environment variable `PWNLIB_DEBUG` or magic argument `DEBUG` (e.g. `python foo.py DEBUG`).
2. For `coin1` I solved it in a similar manner, but used `.recvline()` and then regex to parse it.

**Comment by Idolf** [comment] 2015-02-12 19:22
We already support this usecase through the timeout argument. However I still think this problem is a slight gotcha, and that the documentation should be updated to prevent this kind of confusion in the future.

**Comment by zachriggle** [comment] 2015-02-12 19:25
The timeout argument doesn't come into play here.  The problem is that it's a wrapper around `recvpred`, and his expression was true for both `N=1 C=2` as well as `N=1 C=23`.  `recvpred` stops when the first available match is found, and evaluates the expression by accumulating single bytes.

**Comment by zachriggle** [comment] 2015-02-12 19:33
Also, @gsingh93, there's `recvline_regex` which would have solved the problem.

**Comment by Idolf** [comment] 2016-07-02 20:11
@zachriggle, do you want to revive this, or should we close it?

**Comment by zachriggle** [comment] 2016-07-26 14:35
The PR in #473 was rejected, closing as WONTFIX. A workaround was suggested for the reporter in my comment above (tl;dr `re.DOTALL`).

**Closed by zachriggle** 2016-07-26 14:35 UTC
