### ISSUE TITLE
android example recvall error solution

### ISSUE THREAD

**Issue by zcorrea357** [Gallopsled/pwntools#1714] opened 2020-10-29 16:16 UTC
add .decode () inside rio.recvall to correct the TypeError error: a bytes-like object is required, not 'str'

https://github.com/Gallopsled/pwntools/blob/dev/examples/android.py
```py
from __future__ import print_function

import gdb
from pwn import adb, context

# Tell pwntools that the target is an Android device
context.os = "android"
context.arch = "aarch64"  # or 'arm'

# Optionally, set the remote ADB server address
context.adb_host = "172.16.110.1"

# Wait for a device to become available
print(adb.wait_for_device())

# Who am I?
print(adb.process("id").recvall().strip())

# Interactive sessions!
io = adb.shell()
io.sendline("echo Hello, world; exit")
print(io.recvall().replace("\r\n", "\n").strip())

# Debugging!
gdb.debug("sh").interactive()



>>> print(adb.wait_for_device())
[x] Waiting for device to come online
/usr/lib/python3.8/site-packages/dateutil/parser/_parser.py:1213: UnknownTimezoneWarning: tzname CDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  warnings.warn("tzname {tzname} identified but not understood.  "
[+] Waiting for device to come online: 0050801458 (rhannah OPP27.91-179-8 2019-May-25)
0050801458
>>> 
>>> # Who am I?
>>> print(adb.process("id").recvall().strip())
[!] Automatically selecting device 0050801458
[x] Starting Android process 'id'
[+] Starting Android process 'id': Done
b'uid=2000(shell) gid=2000(shell) groups=2000(shell),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats),3009(readproc) context=u:r:shell:s0'
>>> 
>>> # Interactive sessions!
>>> io = adb.shell()
[x] Starting Android process 'sh'
[+] Starting Android process 'sh': Done
>>> io.sendline("echo Hello, world; exit")
>>> print(io.recvall().decode().replace("\r\n", "\n").strip())
rhannah:/ $ echo Hello, world; exit
Hello, world
>>> 
```

**Comment by zachriggle** [comment] 2020-10-29 16:33
The Android code is effectively unsupported as testing it greatly increases the amount of time tests take to run, and there are not many users.

That said, if you would like to submit a pull request, I'd be glad to merge it.

Note that the current behavior (`.recvall()` returns a `bytes` type) is correct and intended.  If you want to `.replace(str, str)` you need to call `.decode()` on the data yourself.  You could also use `.recvallS` to get a string.

Maybe I'm not noticing the issue you're trying to report?

**Comment by Arusekk** [comment] 2020-10-31 20:27
@zachriggle is right, this is intended behaviour.You can also just use `.replace(b"\r\n", b"\n").decode()` to deal with bytes first, and decode later. Closing this.

**Closed as completed by Arusekk** 2020-10-31 20:27 UTC
Labels: bug, backport-required

**Comment by zachriggle** [comment] 2020-11-02 07:11
The /r/n vs /n is a thing that the ADB binary does and is wrong and not compatible with binary output.

The current behavior, unless it's changed, is correct.
